#!/bin/sh
# C1 — First-boot secret generation.
#
# Writes .secrets/secrets.env with auto-generated values for secrets that
# cannot be self-managed by the Keycloak bootstrap engine (Epic A):
#
#   AUTH_SECRET          — Auth.js session-cookie signing key
#   POSTGRES_PASSWORD    — internal Postgres password
#   KC_ADMIN_PASSWORD    — first-boot Keycloak admin password
#   SCIM_BEARER_TOKEN    — inbound SCIM provisioning bearer token
#   ACCESS_EVAL_TOKEN    — posture-evaluation token (backend ↔ Keycloak SPI)
#   FLEET_WEBHOOK_SECRET — Fleet enrollment-callback HMAC (+ default device-cookie HMAC)
#   PROVISIONING_MASTER_KEY — AES-256-GCM key for stored connector secrets
#
# DEVICE_COOKIE_SECRET is optional and intentionally NOT auto-generated: when
# unset, freecloud-device-id cookies are signed with FLEET_WEBHOOK_SECRET.
# Set DEVICE_COOKIE_SECRET in secrets.env by hand to rotate cookie signing
# independently of the Fleet webhook.
#
# KEYCLOAK_CLIENT_SECRET is absent: Epic A's bootstrap engine self-manages it.
#
# Idempotent: skips generation if all required keys already exist.
# Delete .secrets/secrets.env to rotate all tokens (invalidates all sessions).

set -e

SECRETS_FILE=${SECRETS_FILE:-/run/freecloud/secrets.env}

gen() {
  # 32 random bytes → 64-char hex string (256 bits of entropy).
  head -c 32 /dev/urandom | od -A n -t x1 | tr -d ' \n'
}

gen_b64() {
  # 32 random bytes → base64 string for AES-256 keys.
  head -c 32 /dev/urandom | base64 | tr -d '\n'
}

# Idempotency check.
if [ -f "${SECRETS_FILE}" ]; then
  missing=0
  for key in POSTGRES_PASSWORD KC_ADMIN_PASSWORD AUTH_SECRET SCIM_BEARER_TOKEN ACCESS_EVAL_TOKEN FLEET_WEBHOOK_SECRET PROVISIONING_MASTER_KEY; do
    if ! grep -q "^${key}=" "${SECRETS_FILE}" 2>/dev/null; then
      missing=1
      break
    fi
  done
  if [ "${missing}" -eq 0 ]; then
    echo "[secrets-init] secrets.env already complete — skipping generation"
    exit 0
  fi
  echo "[secrets-init] secrets.env exists but is incomplete — regenerating"
fi

POSTGRES_PASSWORD=$(gen)
KC_ADMIN_PASSWORD=$(gen)
AUTH_SECRET=$(gen)
SCIM_BEARER_TOKEN=$(gen)
ACCESS_EVAL_TOKEN=$(gen)
FLEET_WEBHOOK_SECRET=$(gen)
PROVISIONING_MASTER_KEY=$(gen_b64)

cat > "${SECRETS_FILE}" <<EOF
# Auto-generated by docker/init-secrets/generate.sh on first boot.
# DO NOT EDIT BY HAND. Delete this file to regenerate (rotates all tokens).
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
KC_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
AUTH_SECRET=${AUTH_SECRET}
SCIM_BEARER_TOKEN=${SCIM_BEARER_TOKEN}
ACCESS_EVAL_TOKEN=${ACCESS_EVAL_TOKEN}
FLEET_WEBHOOK_SECRET=${FLEET_WEBHOOK_SECRET}
PROVISIONING_MASTER_KEY=${PROVISIONING_MASTER_KEY}
EOF

chmod 600 "${SECRETS_FILE}"
echo "[secrets-init] wrote ${SECRETS_FILE}"
