#!/bin/sh
# C1 — First-boot secret generation.
#
# Writes .secrets/secrets.env with auto-generated values for secrets that
# cannot be self-managed by the Keycloak bootstrap engine (Epic A):
#
#   AUTH_SECRET          — Auth.js session-cookie signing key
#   SCIM_BEARER_TOKEN    — inbound SCIM provisioning bearer token
#   ACCESS_EVAL_TOKEN    — posture-evaluation token (backend ↔ Keycloak SPI)
#   FLEET_WEBHOOK_SECRET — Fleet enrollment-callback HMAC secret
#
# The internal Postgres password and Keycloak admin password are intentionally
# kept as localhost-only fixed values in docker-compose.localhost.yml because
# they are only reachable within the Docker network and their values are not
# needed at compose-parse time for the URL construction to work.
#
# KEYCLOAK_CLIENT_SECRET is absent: Epic A's bootstrap engine self-manages it.
#
# Idempotent: skips generation if all required keys already exist.
# Delete .secrets/secrets.env to rotate all tokens (invalidates all sessions).

set -e

SECRETS_FILE=/run/freecloud/secrets.env

gen() {
  # 32 random bytes → 64-char hex string (256 bits of entropy).
  head -c 32 /dev/urandom | od -A n -t x1 | tr -d ' \n'
}

# Idempotency check.
if [ -f "${SECRETS_FILE}" ]; then
  missing=0
  for key in AUTH_SECRET SCIM_BEARER_TOKEN ACCESS_EVAL_TOKEN FLEET_WEBHOOK_SECRET; do
    if ! grep -q "^${key}=" "${SECRETS_FILE}" 2>/dev/null; then
      missing=1
      break
    fi
  done
  if [ "${missing}" -eq 0 ]; then
    echo "[secrets-init] secrets.env already complete — skipping generation"
    exit 0
  fi
  echo "[secrets-init] secrets.env exists but is incomplete — regenerating"
fi

AUTH_SECRET=$(gen)
SCIM_BEARER_TOKEN=$(gen)
ACCESS_EVAL_TOKEN=$(gen)
FLEET_WEBHOOK_SECRET=$(gen)

cat > "${SECRETS_FILE}" <<EOF
# Auto-generated by docker/init-secrets/generate.sh on first boot.
# DO NOT EDIT BY HAND. Delete this file to regenerate (rotates all tokens).
AUTH_SECRET=${AUTH_SECRET}
SCIM_BEARER_TOKEN=${SCIM_BEARER_TOKEN}
ACCESS_EVAL_TOKEN=${ACCESS_EVAL_TOKEN}
FLEET_WEBHOOK_SECRET=${FLEET_WEBHOOK_SECRET}
EOF

chmod 600 "${SECRETS_FILE}"
echo "[secrets-init] wrote ${SECRETS_FILE}"
