//go:build e2e

// Package e2e — GeoIP geo-condition enforcement test (A2).
//
// backend-e2e is started with GEOIP_MMDB_PATH pointing at a tiny fixture mmdb
// (generated by `go run ./cmd/genfixturemmdb`, wired in
// docker/docker-compose.e2e.yml) that maps:
//
//	203.0.113.0/24  -> DE
//	198.51.100.0/24 -> US
//
// This proves the live geoip.Resolver (internal/geoip) is actually wired via
// Handler.SetGeoIPLookup end-to-end, not just unit-tested in isolation.
package e2e

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"testing"
	"time"
)

// TestE2E_Admin_GeoCondition_Enforcement creates a geo-restricted app policy
// (geoCountryAllowlist=["DE"]), enrolls a compliant device for a user, and
// proves access/evaluate allows a request whose clientIp resolves to DE and
// denies one that resolves to US.
func TestE2E_Admin_GeoCondition_Enforcement(t *testing.T) {
	waitReady(t, 60*time.Second)
	admin := adminHeaders(t)

	// 1. Create the target app and a geo-restricted policy (DE only).
	appID := createOIDCApp(t, admin, fmt.Sprintf("e2e-geo-app-%d", time.Now().UnixNano()))
	policyBody := map[string]interface{}{
		"requireEnrolled":     false,
		"geoCountryAllowlist": []string{"DE"},
	}
	status, body := do(t, http.MethodPut, "/api/v1/apps/"+appID+"/policy", admin, policyBody)
	if status != http.StatusOK {
		t.Fatalf("upsert app policy: expected 200, got %d: %s", status, body)
	}

	// 2. Create a user and enroll a compliant device (host-001 — the FleetDM
	// mock's built-in compliant host) so the geo condition is the only thing
	// under test; an unenrolled/non-compliant device would deny for a
	// different reason first.
	email := fmt.Sprintf("e2e-geo-%d@example.com", time.Now().UnixNano())
	createUserBody := map[string]interface{}{
		"schemas":  []string{"urn:ietf:params:scim:schemas:core:2.0:User"},
		"userName": email,
		"name":     map[string]string{"givenName": "Geo", "familyName": "Test"},
		"active":   true,
	}
	status, body = do(t, http.MethodPost, "/scim/v2/Users", scimHeaders(), createUserBody)
	if status != http.StatusCreated {
		t.Fatalf("create user via SCIM: expected 201, got %d: %s", status, body)
	}
	var user struct {
		ID string `json:"id"`
	}
	if err := json.Unmarshal(body, &user); err != nil || user.ID == "" {
		t.Fatalf("parse SCIM create-user response: %v (body: %s)", err, body)
	}
	defer do(t, http.MethodDelete, "/scim/v2/Users/"+user.ID, scimHeaders(), nil)

	tokenBody := map[string]string{"userId": user.ID}
	status, body = do(t, http.MethodPost, "/api/v1/e2e/enrollment-token", scimHeaders(), tokenBody)
	if status != http.StatusOK {
		t.Fatalf("create enrollment token: expected 200, got %d: %s", status, body)
	}
	var tokenResp struct {
		Data struct {
			Token string `json:"token"`
		} `json:"data"`
	}
	if err := json.Unmarshal(body, &tokenResp); err != nil || tokenResp.Data.Token == "" {
		t.Fatalf("parse token response: %v (body: %s)", err, body)
	}

	hostID := "host-001" // FleetDM mock's compliant built-in host.
	enrollPayload, _ := json.Marshal(map[string]string{
		"enrollment_token": tokenResp.Data.Token,
		"host_id":          hostID,
		"hostname":         hostID + ".local",
		"os_version":       "macOS 15.0",
	})
	sig := hmacSig(t, *flagWebhookSecret, enrollPayload)
	status, body = do(t, http.MethodPost, "/api/v1/fleet/enrollment-callback",
		map[string]string{"X-Fleet-Signature": sig}, json.RawMessage(enrollPayload))
	if status != http.StatusOK {
		t.Fatalf("enrollment callback: expected 200, got %d: %s", status, body)
	}

	// 3. Evaluate from the "allowed" country (DE, via the fixture mmdb's
	// 203.0.113.0/24 -> DE mapping) — must allow.
	allowEval := map[string]string{
		"userId":   user.ID,
		"deviceId": hostID,
		"appId":    appID,
		"clientIp": "203.0.113.42",
	}
	status, body = do(t, http.MethodPost, "/api/v1/access/evaluate", accessEvalHeaders(), allowEval)
	if status != http.StatusOK {
		t.Fatalf("access/evaluate (DE): expected 200, got %d: %s", status, body)
	}
	var allowResult struct {
		Data accessEvalResp `json:"data"`
	}
	if err := json.Unmarshal(body, &allowResult); err != nil {
		t.Fatalf("parse allow response: %v (body: %s)", err, body)
	}
	if !allowResult.Data.Allow {
		t.Errorf("clientIp in DE (allowlisted): expected allow, got deny (reasons: %v)", allowResult.Data.Reasons)
	}

	// 4. Evaluate from the "disallowed" country (US, via 198.51.100.0/24) —
	// must deny with a geo-specific reason.
	denyEval := map[string]string{
		"userId":   user.ID,
		"deviceId": hostID,
		"appId":    appID,
		"clientIp": "198.51.100.42",
	}
	status, body = do(t, http.MethodPost, "/api/v1/access/evaluate", accessEvalHeaders(), denyEval)
	if status != http.StatusOK {
		t.Fatalf("access/evaluate (US): expected 200, got %d: %s", status, body)
	}
	var denyResult struct {
		Data accessEvalResp `json:"data"`
	}
	if err := json.Unmarshal(body, &denyResult); err != nil {
		t.Fatalf("parse deny response: %v (body: %s)", err, body)
	}
	if denyResult.Data.Allow {
		t.Errorf("clientIp in US (not allowlisted): expected deny, got allow")
	}
	hasGeoReason := false
	for _, r := range denyResult.Data.Reasons {
		if strings.Contains(r, "geo") || strings.Contains(r, "country") {
			hasGeoReason = true
		}
	}
	if !hasGeoReason {
		t.Errorf("clientIp in US: denial reasons don't mention geo/country: %v", denyResult.Data.Reasons)
	}
}
